# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  ldflags:
  - -s -w -X github.com/claudiodangelis/qrcp/version.version={{.Version}} -X github.com/claudiodangelis/qrcp/version.date={{.Date}}
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - 386
  - amd64
  - arm
  - arm64
  goarm:
  - 7
  ignore:
  - goos: darwin
    goarch: 386
archives:
  - format_overrides:
    - goos: windows
      formats: [ tar.gz, zip ]
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^chore:'
release:
  footer: |
    ## Downloads
    | Platform | Download link                                                                                                                |
    |----------|------------------------------------------------------------------------------------------------------------------------------|
    | Linux    | [deb package](https://github.com/claudiodangelis/qrcp/releases/download/{{ .Tag }}/qrcp_{{ .Tag }}_linux_amd64.deb)          |
    | Linux    | [RPM package](https://github.com/claudiodangelis/qrcp/releases/download/{{ .Tag }}/qrcp_{{ .Tag }}_linux_amd64.rpm)          |
    | macOS    | [macOS package](https://github.com/claudiodangelis/qrcp/releases/download/{{ .Tag }}/qrcp_{{ .Tag }}_darwin_amd64.tar.gz)    |
    | Windows  | [Windows package](https://github.com/claudiodangelis/qrcp/releases/download/{{ .Tag }}/qrcp_{{ .Tag }}_windows_amd64.tar.gz) |

    Refer to the list of assets below for all supported platform.
nfpms:
  - homepage: https://qrcp.sh
    maintainer: Claudio d'Angelis <claudiodangelis@gmail.com>
    description: Transfer files over wifi from your computer to your mobile device by scanning a QR code without leaving the terminal.
    license: MIT
    formats:
      - deb
      - rpm
